package org.siraya.rent.pojo;

import java.util.regex.Pattern;

import junit.framework.Assert;
import java.util.Locale;
import org.siraya.rent.utils.RentException;
import org.codehaus.jackson.annotate.JsonIgnore;
public class User {
    private static  Pattern mobilePhonePattern = Pattern.compile("^\\d*$");
    private static  Pattern emailPattern = Pattern.compile("^[A-Za-z0-9._%'-]+@[A-Za-z0-9.-]+\\.[a-zA-Z]{1,4}$");
    private Locale locale= null;
    public static String ENCRYPT_KEY = "general";
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ID
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.MOBILE_PHONE
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.EMAIL
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.LOGIN_ID
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.LOGIN_TYPE
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private Integer loginType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.PASSWORD
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.TIMEZONE
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private String timezone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.NATIONAL_ID
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private String nationalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.CC
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private String cc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.LANG
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private String lang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.STATUS
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.CREATED
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private Long created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.MODIFIED
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    private Long modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.ID
     *
     * @return the value of USER.ID
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.ID
     *
     * @param id the value for USER.ID
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.MOBILE_PHONE
     *
     * @return the value of USER.MOBILE_PHONE
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
	@JsonIgnore
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.MOBILE_PHONE
     *
     * @param mobilePhone the value for USER.MOBILE_PHONE
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    public void validate(String key, String value) {
    	if (!mobilePhonePattern.matcher(value).find()) {
    		throw new RentException(RentException.RentErrorCode.ErrorInvalidParameter,
    				"phone number format error "+value);
    	}	
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.EMAIL
     *
     * @return the value of USER.EMAIL
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public String getEmail() {

        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.EMAIL
     *
     * @param email the value for USER.EMAIL
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public void verifyEmail(){
		if (email != null && email != "") {
			Assert.assertTrue("email format error", emailPattern
				.matcher(email).find());    	
		}
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.LOGIN_ID
     *
     * @return the value of USER.LOGIN_ID
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.LOGIN_ID
     *
     * @param loginId the value for USER.LOGIN_ID
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.LOGIN_TYPE
     *
     * @return the value of USER.LOGIN_TYPE
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public Integer getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.LOGIN_TYPE
     *
     * @param loginType the value for USER.LOGIN_TYPE
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setLoginType(Integer loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.PASSWORD
     *
     * @return the value of USER.PASSWORD
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
	@JsonIgnore
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.PASSWORD
     *
     * @param password the value for USER.PASSWORD
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.TIMEZONE
     *
     * @return the value of USER.TIMEZONE
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.TIMEZONE
     *
     * @param timezone the value for USER.TIMEZONE
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setTimezone(String timezone) {
        this.timezone = timezone == null ? null : timezone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.NATIONAL_ID
     *
     * @return the value of USER.NATIONAL_ID
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
	@JsonIgnore
    public String getNationalId() {
        return nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.NATIONAL_ID
     *
     * @param nationalId the value for USER.NATIONAL_ID
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setNationalId(String nationalId) {
        this.nationalId = nationalId == null ? null : nationalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.CC
     *
     * @return the value of USER.CC
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public String getCc() {
        return cc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.CC
     *
     * @param cc the value for USER.CC
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setCc(String cc) {
        this.cc = cc == null ? null : cc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.LANG
     *
     * @return the value of USER.LANG
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.LANG
     *
     * @param lang the value for USER.LANG
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setLang(String lang) {
        this.lang = lang == null ? null : lang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.STATUS
     *
     * @return the value of USER.STATUS
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.STATUS
     *
     * @param status the value for USER.STATUS
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.CREATED
     *
     * @return the value of USER.CREATED
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public Long getCreated() {
		if (created == null || created == 0) {
			created=java.util.Calendar.getInstance().getTimeInMillis()/1000;
			modified= created;
		}
    	return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.CREATED
     *
     * @param created the value for USER.CREATED
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.MODIFIED
     *
     * @return the value of USER.MODIFIED
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public Long getModified() {
		if (modified == null || modified == 0) {
			modified=java.util.Calendar.getInstance().getTimeInMillis()/1000;
		}
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.MODIFIED
     *
     * @param modified the value for USER.MODIFIED
     *
     * @mbggenerated Mon Sep 10 16:50:24 CST 2012
     */
    public void setModified(Long modified) {
        this.modified = modified;
    }

    /**
     * get locale from language and country
     * @return
     */
    public Locale getLocale(){
    	if (locale == null) {
    		locale = new Locale(this.lang, this.cc, "");
    	}
    	return locale;
    }
}