<script id="tmpl_register_step3" type="x-tmpl-mustache">
<header>
<div id="fb-root"></div>
	<div class="row">
		<div class="span3">
			<ul class="breadcrumb">
				<li>
					<a href="#home">Home</a>
					<span class="divider">/</span>
				</li>
				<li class="active" id="register_title"></li>
			</ul>
		</div>
	</div>
</header>
<div class="row">
	<div class="span4">
		<div id="auth_success_block" style="display:none">
			<div class="alert alert-success">
				<span  id="i18n_auth_success"></span>
			</div>
		</div>
	</div>
</div>
<div class="row">
<div class="span3">
	<div class="well">
    	<ul class="nav nav-pills nav-stacked">
			<li><a href="#main/mobile_provider" id="i18n_mobile_provider"></a></li>
			<li><a href="#main/name_device" id="i18n_named_my_devices"></a></li>
			<li><a href="#main/show_user_profile" id="i18n_user_profile"></a></li>
			<li><a href="#main/show_my_device" id="i18n_show_my_devices"></a></li>
{{#user}}
	{{^is_fb}}
			<li id="link_to_fb_link"><a id="i18n_link_fb"></a></li>
	{{/is_fb}} 
			<li id="list_members_link"><a href="#main/list_members" id="i18n_list_members"></a></li>
			<li id="sso_application_link"><a href="#main/sso_application" id="i18n_sso_application"></a></li>
{{/user}}

			<li id="sign_off_link"><a id="i18n_delete_device"></a></li>
	    </ul>
	</div> 
</div> 
<div id="register_right" class="span9">
</div>
</div>
</script>