<script id="tmpl_show_fb_friends" type="x-tmpl-mustache">
<div class="row">
	<div class="span6">
    	<h4 id="i18n_import_fb_friends"></h4>
	</div>
</div>
<div class="row">
	<div class="span6">
		<table id="friend_table" class="table table-striped">
			<thead>
				<tr>
					<td><span class="i18n_name"></span></td>
					<td></td>
					<td></td>
				</tr>
			</thead>
			<tbody>
{{#sliceFriends}}
				<tr id="{{id}}">
					<td class="show_sessions_link">{{name}}</td>
					<td><img src="https://graph.facebook.com/{{id}}/picture"></td>
					<td><a href="#" class="close delete_friend_link">x</a></td>
				</tr>
{{/sliceFriends}}
			</tbody>
		</table>

	</div>
</div>
<div class="row">
	<div class="span6">
    	<form  id="import_members_form" class="form-horizontal">
			<button class="btn btn-success" type="button" id="create_members_link"></button>
        </form>
	</div>
</div>
</script>