<script id="tmpl_link_fb" type="x-tmpl-mustache">
<div class="span7 offset1">
    <form id="link_fb_form" class="form-horizontal well">
        <h4>Warning!</h4>
		<p class="text-info">
			This user will be linked to Facebook account <strong>{{name}}</strong> 
			<img src="https://graph.facebook.com/{{id}}/picture">
		</p>
		<p class="text-info">
		Do you want to continue?
		</p>
		<div class="form-actions">
			<button id="link_fb_ok" class="btn btn-primary" type="button">Yes</button>
			<!--button class="btn btn-primary" type="button">Change to anther account</button-->
			<!--button id="link_fb_no" class="btn btn-primary" type="button">No, thanks</button-->
		</div>
    </form>
</div>
</script>