mobile_country_code: 
    886:
       country: TW
       lang: zh
       timezone: Taipei
    86:
       country: CN
       lang: zh
       timezone: Beijing
filter:
    exclude: ['^sently_callback']
general:
    max_device_count: 3
    max_user_per_device: 3
    auth_retry_limit: 3
    auth_verify_timeout : 1800
    admin_user: 00000000
    debug: true 
sently:
    username: semistone
    password: semistone
    debug: true
    callback_pass: 123456789
keydb:
    cookie: thebestsecretkey
    general: thebestsecretkey