mobile_country_code: 
    "886":
       country: TW
       lang: zh-TW
       timezone: Taipei
    "86":
       country: CN
       lang: zh-CN
       timezone: Beijing
filter:
    exclude: ['^sently_callback']
general:
    max_device_count: 10
    max_user_per_device: 10
    auth_retry_limit: 10
    auth_verify_timeout : 1800
    admin_user: 00000000
    callback_max_retry : 10
    debug: true
    geoip_data: 'C:/Users/User/Downloads'
    tmp_dir: d:/tmp
    base_url: http://localhost:8080/rent/rest
sently:
    username: semistone
    password: semistone
    debug: true
    callback_pass: 123456789
    max_msgs_per_day : 100
keydb:
    cookie: thebestsecretkey
    general: thebestsecretkey
web:
    cdn: 'http://ec2-54-251-33-245.ap-southeast-1.compute.amazonaws.com'
repl:
    log_writers: 
        queue1: 
            readers: [reader1,reader2]
        queue2: 
            param1: xyz
        test: 
            param1: xyz
    log_readers:
        reader1:
            type: relay
            relay_to: http://localhost:8080/rent/rest/repl/queue2
        reader2:
            type: bean
                                  
    volumn_max_entity: 5000
dropbox:
    app_key: test
    app_secret: test
    toekn_key: test
    token_secret: test
    retrieve_token_path : /dropbox/retrieve_token
image:
    ext: ['png', 'gif', 'jpg']
    limit: [4000,2000]
    max_pics_per_group: 10