mobile_country_code: 
    886:
       country: TW
       lang: zh-TW
       timezone: Taipei
    86:
       country: CN
       lang: zh-CN
       timezone: Beijing
general:
    max_device_count: 3
    auth_retry_limit: 3
    auth_verify_timeout : 1800
sently:
    username: semistone
    password: semistone
    debug: true